### ISSUE TITLE
Building trigger off/on when raccoon is grounded

### ISSUE THREAD

**Issue by spaghettioh** [spaghettioh/2019-github-gameoff#4]
If raccoon is grounded, building collider is trigger
If raccoon is not grounded, building collider is not trigger

**Comment by bjshively** [comment]
Prototype in 12ebdcbc2899a53a34c52281714e6eaddb6863b0

Considering this done for now as it seems a bit buggy/error prone, and we may just want to use 1 way platforms. Will revisit later.
